<?php

function brViewsCustom_views_query_alter(&$view, &$query) {
  if ($view->name == 'brexit_hub' && $view->current_display == 'block') {
     $query->table_queue['taxonomy_index']['join']->type = "LEFT OUTER";
    $query->orderby = array(
	  array(
        'field' => 'CASE '
      . 'WHEN field_data_field_l_date.field_l_date_value '
      . 'THEN field_data_field_l_date.field_l_date_value '
      . 'ELSE node.created END',
        'direction' => 'DESC',
      )
    );
  }
}