preferred_syntax = :sass
http_path = '/'
css_dir = 'css'
sass_dir = 'scss'
images_dir = 'images'
javascripts_dir = 'js'
relative_assets = true
line_comments = true
precision=8
sourcemap = true
output_style = :compressed