<?php

function brVcard_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'people_node_form':
      if ($form['#node']->nid) {
        if (isset($_GET['vcard'])) {
          require_once(drupal_get_path('module', 'brVcard') . '/vcard.php');
          $vc = new vcard();
          $vc->data = array(
            'display_name' => $form['#node']->title,
            'first_name' => $form['#node']->field_people_fname[LANGUAGE_NONE][0]['value'],
            'last_name' => $form['#node']->field_people_sname[LANGUAGE_NONE][0]['value'],
            'company' => 'Brodies LLP',
            'title' => $form['#node']->field_people_job[LANGUAGE_NONE][0]['value'],
            'work_city' => db_query("SELECT title FROM {node} where nid = :nid", array(':nid' => $form['#node']->field_people_location[0]['nid']))->fetchField(),
            'office_tel' => $form['#node']->field_people_phone[LANGUAGE_NONE][0]['value'],
            'email1' => $form['#node']->field_people_email[LANGUAGE_NONE][0]['value'],
            'url' => url('node/' . $form['#node']->nid, array('absolute' => TRUE)),
            'photo' => image_style_url('medium', $form['#node']->field_teaser_image[LANGUAGE_NONE][0]['uri'])
          );

          $vc->download();
          exit();
        }
        $form['#prefix'] = l(t('Generate vCard file from details below'), $_GET['q'], array('query' => array('vcard' => TRUE)));
      }
      break;
  }
}
